-- ***********************************************************************************************************************************************************************
----- DROP OTHER CONSTRAINTS ----- DROP OTHER CONSTRAINTS ----- DROP OTHER CONSTRAINTS ----- DROP OTHER CONSTRAINTS ----- DROP OTHER CONSTRAINTS ----- DROP OTHER CONSTRAINTS -----
--DROP TRAINER id
IF OBJECT_ID('[dbo].[ID_CONSTR_TRAINER]') IS NOT NULL 
ALTER TABLE [dbo].[TRAINER] DROP CONSTRAINT [ID_CONSTR_TRAINER]
GO
--DROP JOCKEY id
IF OBJECT_ID('[dbo].[ID_CONSTR_JOCKEY]') IS NOT NULL 
ALTER TABLE [dbo].[JOCKEY] DROP CONSTRAINT [ID_CONSTR_JOCKEY]
GO
-- DROP BREEDER id
IF OBJECT_ID('[dbo].[ID_CONSTR_BREEDER]') IS NOT NULL 
ALTER TABLE [dbo].[BREEDER] DROP CONSTRAINT [ID_CONSTR_BREEDER] 
GO
-- DROP OWNER id
IF OBJECT_ID('[dbo].[ID_CONSTR_OWNER]') IS NOT NULL 
ALTER TABLE [dbo].[OWNER] DROP CONSTRAINT [ID_CONSTR_OWNER] 
GO
-- DROP [USER_ROLE_DOMAIN]
IF OBJECT_ID('[dbo].[USER_ROLE_DOMAIN]') IS NOT NULL 
ALTER TABLE [dbo].[SYSTEM_USER] DROP CONSTRAINT [USER_ROLE_DOMAIN]
GO
-- DROP [HORSE_SEX_DOMAIN]
IF OBJECT_ID('[dbo].[HORSE_SEX_DOMAIN]') IS NOT NULL 
ALTER TABLE [dbo].[HORSE] DROP CONSTRAINT [HORSE_SEX_DOMAIN]
GO
-- DROP [OWNER_TITLE_DOMAIN]
IF OBJECT_ID('[dbo].[OWNER_TITLE_DOMAIN]') IS NOT NULL 
ALTER TABLE [dbo].[OWNER] DROP CONSTRAINT [OWNER_TITLE_DOMAIN]
GO
-- DROP [PRIZE1_CONSTR_RACE]
IF OBJECT_ID('[dbo].[PRIZE1_CONSTR_RACE]') IS NOT NULL 
ALTER TABLE [dbo].[RACE] DROP CONSTRAINT [PRIZE1_CONSTR_RACE]
GO
-- DROP [OWNER_TITLE_DOMAIN]
IF OBJECT_ID('[dbo].[PRIZE2_CONSTR_RACE]') IS NOT NULL 
ALTER TABLE [dbo].[RACE] DROP CONSTRAINT [PRIZE2_CONSTR_RACE]
GO

-- ***********************************************************************************************************************************************************************
---- DROP FOREIGN KEY CONSTRAINTS ---- DROP FOREIGN KEY CONSTRAINTS ---- DROP FOREIGN KEY CONSTRAINTS ---- DROP FOREIGN KEY CONSTRAINTS ---- DROP FOREIGN KEY CONSTRAINTS-

--HORSE FK DROP
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_HORSE_HORSE_MOM]') AND parent_object_id = OBJECT_ID(N'[dbo].[HORSE]'))
ALTER TABLE [dbo].[HORSE] DROP CONSTRAINT [FK_HORSE_HORSE_MOM]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_HORSE_HORSE_DAD]') AND parent_object_id = OBJECT_ID(N'[dbo].[HORSE]'))
ALTER TABLE [dbo].[HORSE] DROP CONSTRAINT [FK_HORSE_HORSE_DAD]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_HORSE_JOCKEY]') AND parent_object_id = OBJECT_ID(N'[dbo].[HORSE]'))
ALTER TABLE [dbo].[HORSE] DROP CONSTRAINT [FK_HORSE_JOCKEY]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_HORSE_HORSE_COLOR]') AND parent_object_id = OBJECT_ID(N'[dbo].[HORSE]'))
ALTER TABLE [dbo].[HORSE] DROP CONSTRAINT [FK_HORSE_HORSE_COLOR]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_HORSE_TRAINER]') AND parent_object_id = OBJECT_ID(N'[dbo].[HORSE]'))
ALTER TABLE [dbo].[HORSE] DROP CONSTRAINT [FK_HORSE_TRAINER]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_HORSE_OWNER]') AND parent_object_id = OBJECT_ID(N'[dbo].[HORSE]'))
ALTER TABLE [dbo].[HORSE] DROP CONSTRAINT [FK_HORSE_OWNER]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_HORSE_HORSE_COLOR]') AND parent_object_id = OBJECT_ID(N'[dbo].[HORSE]'))
ALTER TABLE [dbo].[HORSE] DROP CONSTRAINT [FK_HORSE_HORSE_COLOR]
GO
-- USER CREATE AND UPDATE DROP
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_HORSE_USER_CREATE]') AND parent_object_id = OBJECT_ID(N'[dbo].[HORSE]'))
ALTER TABLE [dbo].[HORSE] DROP CONSTRAINT [FK_HORSE_USER_CREATE]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_HORSE_USER_UPDATE]') AND parent_object_id = OBJECT_ID(N'[dbo].[HORSE]'))
ALTER TABLE [dbo].[HORSE] DROP CONSTRAINT [FK_HORSE_USER_UPDATE]
GO

-- HORSE_COLOR FK DROP
-- USER CREATE AND UPDATE DROP
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_HORSE_COLOR_USER_CREATE]') AND parent_object_id = OBJECT_ID(N'[dbo].[HORSE_COLOR]'))
ALTER TABLE [dbo].[HORSE_COLOR] DROP CONSTRAINT [FK_HORSE_COLOR_USER_CREATE]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_HORSE_COLOR_USER_UPDATE]') AND parent_object_id = OBJECT_ID(N'[dbo].[HORSE_COLOR]'))
ALTER TABLE [dbo].[HORSE_COLOR] DROP CONSTRAINT [FK_HORSE_COLOR_USER_UPDATE]
GO

-- JOCKEY FK DROP
-- USER CREATE AND UPDATE DROP
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_JOCKEY_USER_CREATE]') AND parent_object_id = OBJECT_ID(N'[dbo].[JOCKEY]'))
ALTER TABLE [dbo].[JOCKEY] DROP CONSTRAINT [FK_JOCKEY_USER_CREATE]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_JOCKEY_USER_UPDATE]') AND parent_object_id = OBJECT_ID(N'[dbo].[JOCKEY]'))
ALTER TABLE [dbo].[JOCKEY] DROP CONSTRAINT [FK_JOCKEY_USER_UPDATE]
GO

-- MEETING FK DROP
-- USER CREATE AND UPDATE DROP
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_MEETING_USER_CREATE]') AND parent_object_id = OBJECT_ID(N'[dbo].[MEETING]'))
ALTER TABLE [dbo].[MEETING] DROP CONSTRAINT [FK_MEETING_USER_CREATE]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_MEETING_USER_UPDATE]') AND parent_object_id = OBJECT_ID(N'[dbo].[MEETING]'))
ALTER TABLE [dbo].[MEETING] DROP CONSTRAINT [FK_MEETING_USER_UPDATE]
GO

-- RACE FK DROP
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_RACE_RACE_TYPE]') AND parent_object_id = OBJECT_ID(N'[dbo].[RACE]'))
ALTER TABLE [dbo].[RACE] DROP CONSTRAINT [FK_RACE_RACE_TYPE]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_RACE_FIELD_TYPE]') AND parent_object_id = OBJECT_ID(N'[dbo].[RACE]'))
ALTER TABLE [dbo].[RACE] DROP CONSTRAINT [FK_RACE_FIELD_TYPE]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_RACE_MEETING]') AND parent_object_id = OBJECT_ID(N'[dbo].[RACE]'))
ALTER TABLE [dbo].[RACE] DROP CONSTRAINT [FK_RACE_MEETING]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_RACE_DISTANCE]') AND parent_object_id = OBJECT_ID(N'[dbo].[RACE]'))
ALTER TABLE [dbo].[RACE] DROP CONSTRAINT [FK_RACE_DISTANCE]
GO
-- USER CREATE AND UPDATE DROP
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_RACE_USER_CREATE]') AND parent_object_id = OBJECT_ID(N'[dbo].[RACE]'))
ALTER TABLE [dbo].[RACE] DROP CONSTRAINT [FK_RACE_USER_CREATE]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_RACE_USER_UPDATE]') AND parent_object_id = OBJECT_ID(N'[dbo].[RACE]'))
ALTER TABLE [dbo].[RACE] DROP CONSTRAINT [FK_RACE_USER_UPDATE]
GO

-- RACE_DISTANCE FK DROP
--FOREIGN KEYS FOR USER --
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_RACE_DISTANCE_USER_CREATE]') AND parent_object_id = OBJECT_ID(N'[dbo].[RACE_DISTANCE]'))
ALTER TABLE [dbo].[RACE_DISTANCE] DROP CONSTRAINT [FK_RACE_DISTANCE_USER_CREATE]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_RACE_DISTANCE_USER_UPDATE]') AND parent_object_id = OBJECT_ID(N'[dbo].[RACE_DISTANCE]'))
ALTER TABLE [dbo].[RACE_DISTANCE] DROP CONSTRAINT [FK_RACE_DISTANCE_USER_UPDATE]
GO

--TRAINER FK DROP
--FOREIGN KEYS FOR USER --
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TRAINER_USER_CREATE]') AND parent_object_id = OBJECT_ID(N'[dbo].[TRAINER]'))
ALTER TABLE [dbo].[TRAINER] DROP CONSTRAINT [FK_TRAINER_USER_CREATE]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TRAINER_USER_UPDATE]') AND parent_object_id = OBJECT_ID(N'[dbo].[TRAINER]'))
ALTER TABLE [dbo].[TRAINER] DROP CONSTRAINT [FK_TRAINER_USER_UPDATE]
GO

--RACE_TYPE FK DROP
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_RACE_TYPE_CREATE]') AND parent_object_id = OBJECT_ID(N'[dbo].[RACE_TYPE]'))
ALTER TABLE [dbo].[RACE_TYPE] DROP CONSTRAINT [FK_RACE_TYPE_USER_CREATE]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TRACE_TYPE_UPDATE]') AND parent_object_id = OBJECT_ID(N'[dbo].[RACE_TYPE]'))
ALTER TABLE [dbo].[RACE_TYPE] DROP CONSTRAINT [FK_RACE_TYPE_USER_UPDATE]
GO

--FIELD_TYPE FK DROP
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_FIELD_TYPE_USER_CREATE]') AND parent_object_id = OBJECT_ID(N'[dbo].[FIELD_TYPE]'))
ALTER TABLE [dbo].[FIELD_TYPE] DROP CONSTRAINT [FK_FIELD_TYPE_USER_CREATE]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_FIELD_TYPE_USER_UPDATE]') AND parent_object_id = OBJECT_ID(N'[dbo].[FIELD_TYPE]'))
ALTER TABLE [dbo].[FIELD_TYPE] DROP CONSTRAINT [FK_FIELD_TYPE_USER_UPDATE]
GO

--BREEDER FK DROP
--FOREIGN KEYS FOR USER --
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_BREEDER_USER_CREATE]') AND parent_object_id = OBJECT_ID(N'[dbo].[BREEDER]'))
ALTER TABLE [dbo].[BREEDER] DROP CONSTRAINT [FK_BREEDER_USER_CREATE]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_BREEDER_USER_UPDATE]') AND parent_object_id = OBJECT_ID(N'[dbo].[BREEDER]'))
ALTER TABLE [dbo].[BREEDER] DROP CONSTRAINT [FK_BREEDER_USER_UPDATE]
GO

--FAMILY FK DROP
--FOREIGN KEYS FOR USER --
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_FAMILY_USER_CREATE]') AND parent_object_id = OBJECT_ID(N'[dbo].[FAMILY]'))
ALTER TABLE [dbo].[FAMILY] DROP CONSTRAINT [FK_FAMILY_USER_CREATE]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_FAMILY_USER_UPDATE]') AND parent_object_id = OBJECT_ID(N'[dbo].[FAMILY]'))
ALTER TABLE [dbo].[FAMILY] DROP CONSTRAINT [FK_FAMILY_USER_UPDATE]
GO


-- PARTICIPATION FK DROP
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_PARTICIPATION_RACE]') AND parent_object_id = OBJECT_ID(N'[dbo].[PARTICIPATION]'))
ALTER TABLE [dbo].[PARTICIPATION] DROP CONSTRAINT [FK_PARTICIPATION_RACE]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_PARTICIPATION_HORSE]') AND parent_object_id = OBJECT_ID(N'[dbo].[PARTICIPATION]'))
ALTER TABLE [dbo].[PARTICIPATION] DROP CONSTRAINT [FK_PARTICIPATION_HORSE]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_PARTICIPATION_JOCKEY]') AND parent_object_id = OBJECT_ID(N'[dbo].[PARTICIPATION]'))
ALTER TABLE [dbo].[PARTICIPATION] DROP CONSTRAINT [FK_PARTICIPATION_JOCKEY]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_PARTICIPATION_TRAINER]') AND parent_object_id = OBJECT_ID(N'[dbo].[PARTICIPATION]'))
ALTER TABLE [dbo].[PARTICIPATION] DROP CONSTRAINT [FK_PARTICIPATION_TRAINER]
GO
--FOREIGN KEYS FOR USER --
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_PARTICIPATION_USER_CREATE]') AND parent_object_id = OBJECT_ID(N'[dbo].[PARTICIPATION]'))
ALTER TABLE [dbo].[PARTICIPATION] DROP CONSTRAINT [FK_PARTICIPATION_USER_CREATE]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_PARTICIPATION_USER_UPDATE]') AND parent_object_id = OBJECT_ID(N'[dbo].[PARTICIPATION]'))
ALTER TABLE [dbo].[PARTICIPATION] DROP CONSTRAINT [FK_PARTICIPATION_USER_UPDATE]
GO

-- OWNER FK DROP
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_OWNER]') AND parent_object_id = OBJECT_ID(N'[dbo].[OWNER]'))
ALTER TABLE [dbo].[OWNER] DROP CONSTRAINT [FK_OWNER]
GO

--FOREIGN KEYS FOR USER --
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_OWNER_USER_CREATE]') AND parent_object_id = OBJECT_ID(N'[dbo].[OWNER]'))
ALTER TABLE [dbo].[OWNER] DROP CONSTRAINT [FK_OWNER_USER_CREATE]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_OWNER_USER_UPDATE]') AND parent_object_id = OBJECT_ID(N'[dbo].[OWNER]'))
ALTER TABLE [dbo].[OWNER] DROP CONSTRAINT [FK_OWNER_USER_UPDATE]
GO

--SYSTEM_USER
--FOREIGN KEYS FOR USER --
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_SYSTEM_USER_USER_CREATE]') AND parent_object_id = OBJECT_ID(N'[dbo].[SYSTEM_USER]'))
ALTER TABLE [dbo].[SYSTEM_USER] DROP CONSTRAINT [FK_SYSTEM_USER_USER_CREATE]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_SYSTEM_USER_USER_UPDATE]') AND parent_object_id = OBJECT_ID(N'[dbo].[SYSTEM_USER]'))
ALTER TABLE [dbo].[SYSTEM_USER] DROP CONSTRAINT [FK_SYSTEM_USER_USER_UPDATE]
GO
-- ***********************************************************************************************************************************************************************
------ DROP TABLES ------ DROP TABLES ------ DROP TABLES ------ DROP TABLES ------ DROP TABLES ------ DROP TABLES ------ DROP TABLES ------ DROP TABLES ------ DROP TABLES

-- DROP HORSE
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[HORSE]') AND type in (N'U'))
DROP TABLE [dbo].[HORSE]
GO
-- DROP HORSE_COLOR
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[HORSE_COLOR]') AND type in (N'U'))
DROP TABLE [dbo].[HORSE_COLOR]
GO
-- DROP JOCKEY
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[JOCKEY]') AND type in (N'U'))
DROP TABLE [dbo].[JOCKEY]
GO
-- DROP JOCKEY
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[JOCKEY]') AND type in (N'U'))
DROP TABLE [dbo].[JOCKEY]
GO
-- DROP MEETING
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MEETING]') AND type in (N'U'))
DROP TABLE [dbo].[MEETING]
GO
-- DROP RACE
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RACE]') AND type in (N'U'))
DROP TABLE [dbo].[RACE]
GO
-- DROP RACE_TYPE
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RACE_TYPE]') AND type in (N'U'))
DROP TABLE [dbo].[RACE_TYPE]
GO
-- DROP FIELD_TYPE
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FIELD_TYPE]') AND type in (N'U'))
DROP TABLE [dbo].[FIELD_TYPE]
GO
-- DROP PARTICIPATION
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PARTICIPATION]') AND type in (N'U'))
DROP TABLE [dbo].[PARTICIPATION]
GO
-- DROP TRAINER
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRAINER]') AND type in (N'U'))
DROP TABLE [dbo].[TRAINER]
GO
-- DROP BREEDER
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BREEDER]') AND type in (N'U'))
DROP TABLE [dbo].[BREEDER]
GO
-- DROP OWNER
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[OWNER]') AND type in (N'U'))
DROP TABLE [dbo].[OWNER]
GO
-- DROP FAMILY
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FAMILY]') AND type in (N'U'))
DROP TABLE [dbo].[FAMILY]
GO
-- DROP USER
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SYSTEM_USER]') AND type in (N'U'))
DROP TABLE [dbo].[SYSTEM_USER]
GO
-- DROP RACE_DISTANCE
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RACE_DISTANCE]') AND type in (N'U'))
DROP TABLE [dbo].[RACE_DISTANCE]
GO
-- DROP SYSTEM_USER
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SYSTEM_USER]') AND type in (N'U'))
DROP TABLE [dbo].[SYSTEM_USER]
GO
-- DROP HORSE_SEX
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[HORSE_SEX]') AND type in (N'U'))
DROP TABLE [dbo].[HORSE_SEX]
GO

-- DROP RACE_RESULTS
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RACE_RESULTS]') AND type in (N'U'))
DROP TABLE [dbo].[RACE_RESULTS]
GO

-- DROP RACE_FIELDS
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RACE_FIELDS]') AND type in (N'U'))
DROP TABLE [dbo].[RACE_FIELDS]
GO









